services:
  embeddings-db:
    image: 'pgvector/pgvector:pg16'
    container_name: 'embeddings-db'
    environment:
      POSTGRES_DB: embeddings-db
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - 5432
    ports:
      - '15433:5432'
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  pgdata:
  ollama_data:
networks:
  embeddings:

