server:
  port: 8080
spring:
  application:
    name: embeddings-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15433/embeddings-db
    username: postgres
    password: 1234
  flyway:
    user: postgres
    password: 1234
    schemas: public
    baselineOnMigrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
      boot:
        allow_jdbc_metadata_access: false
    properties:
      jpa:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

frontend:
  url: http://localhost:5173
quiz:
  similarity:
    threshold: ${QUIZ_SIMILARITY_THRESHOLD:0.8}
ollama:
  url: ${OLLAMA_URL:http://localhost:11434}
  embedModel: ${OLLAMA_EMBEDDING_MODEL:nomic-embed-text}
  model: nomic-embed-text

logging:
  file:
    path: resources/logs
  level:
    org.springframework.security: DEBUG
logback:
  rollingpolicy:
    max-file-size: 100MB
    max-history: 30
    total-size-cap: 300MB
